-- MySQL Script generated by MySQL Workbench
-- qui 18 jul 2024 13:38:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema transferencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transferencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transferencia` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `transferencia` ;

-- -----------------------------------------------------
-- Table `transferencia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferencia`.`usuario` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `empresa` VARCHAR(45) NULL DEFAULT NULL,
  `adm` TINYINT(1) NULL DEFAULT '0',
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `dark_theme` TINYINT(1) NULL DEFAULT '0',
  `perfil` VARCHAR(20) NULL DEFAULT 'visitante',
  `first_login` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transferencia`.`dado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferencia`.`dado` (
  `id_dado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL DEFAULT NULL,
  `download_status` VARCHAR(15) NULL DEFAULT NULL,
  `download_start_datetime` DATETIME NULL DEFAULT NULL,
  `download_end_datetime` DATETIME NULL DEFAULT NULL,
  `md5_cp_status` VARCHAR(15) NULL DEFAULT NULL,
  `md5_cp_start_datetime` DATETIME NULL DEFAULT NULL,
  `md5_cp_end_datetime` DATETIME NULL DEFAULT NULL,
  `md5_validated` TINYINT(1) NULL DEFAULT NULL,
  `md5_validated_datetime` DATETIME NULL DEFAULT NULL,
  `storing_status` VARCHAR(15) NULL DEFAULT NULL,
  `storing_start_datetime` DATETIME NULL DEFAULT NULL,
  `storing_end_datetime` DATETIME NULL DEFAULT NULL,
  `retry_user` INT UNSIGNED NULL DEFAULT NULL,
  `retry_datetime` DATETIME NULL DEFAULT NULL,
  `filesize` BIGINT NULL DEFAULT NULL,
  `date_cba` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dado`),
  INDEX `fk_dado_retry_user` (`retry_user` ASC) VISIBLE,
  CONSTRAINT `fk_dado_retry_user`
    FOREIGN KEY (`retry_user`)
    REFERENCES `transferencia`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 3371
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transferencia`.`dado_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferencia`.`dado_historico` (
  `id_dado_historico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_dado` INT UNSIGNED NULL DEFAULT NULL,
  `nome` VARCHAR(80) NULL DEFAULT NULL,
  `download_status` VARCHAR(15) NULL DEFAULT NULL,
  `download_start_datetime` DATETIME NULL DEFAULT NULL,
  `download_end_datetime` DATETIME NULL DEFAULT NULL,
  `md5_cp_status` VARCHAR(15) NULL DEFAULT NULL,
  `md5_cp_start_datetime` DATETIME NULL DEFAULT NULL,
  `md5_cp_end_datetime` DATETIME NULL DEFAULT NULL,
  `md5_validated` TINYINT(1) NULL DEFAULT NULL,
  `md5_validated_datetime` DATETIME NULL DEFAULT NULL,
  `storing_status` VARCHAR(15) NULL DEFAULT NULL,
  `storing_start_datetime` DATETIME NULL DEFAULT NULL,
  `storing_end_datetime` DATETIME NULL DEFAULT NULL,
  `retry_user` INT UNSIGNED NULL DEFAULT NULL,
  `retry_datetime` DATETIME NULL DEFAULT NULL,
  `filesize` BIGINT NULL DEFAULT NULL,
  `date_cba` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dado_historico`),
  INDEX `fk_dado_historico_retry_user` (`retry_user` ASC) VISIBLE,
  INDEX `fk_dado_historico_id_dado` (`id_dado` ASC) VISIBLE,
  CONSTRAINT `fk_dado_historico_id_dado`
    FOREIGN KEY (`id_dado`)
    REFERENCES `transferencia`.`dado` (`id_dado`),
  CONSTRAINT `fk_dado_historico_retry_user`
    FOREIGN KEY (`retry_user`)
    REFERENCES `transferencia`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 476
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transferencia`.`dado_retry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferencia`.`dado_retry` (
  `id_dado_retry` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_dado` INT UNSIGNED NULL DEFAULT NULL,
  `nome` VARCHAR(80) NULL DEFAULT NULL,
  `error` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dado_retry`),
  INDEX `fK_dado_retry_id_dado` (`id_dado` ASC) VISIBLE,
  CONSTRAINT `fK_dado_retry_id_dado`
    FOREIGN KEY (`id_dado`)
    REFERENCES `transferencia`.`dado` (`id_dado`))
ENGINE = InnoDB
AUTO_INCREMENT = 445
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `transferencia`.`md5_cba_zerado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transferencia`.`md5_cba_zerado` (
  `id_md5_cba_zerado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_dado` VARCHAR(80) NULL DEFAULT NULL,
  `registro_datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_md5_cba_zerado`))
ENGINE = InnoDB
AUTO_INCREMENT = 194
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
